version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    assignees:
      - "mkobit"
    cooldown:
      default-days: 14
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    assignees:
      - "mkobit"
    cooldown:
      default-days: 14
