name: Setup Node.js and PNPM

description: Checks out code, sets up Node.js and pnpm, and caches dependencies.

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        cache: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "25.2.1"

    - name: Cache build and lint artifacts
      uses: actions/cache@v4
      with:
        path: |
          .astro
          .eslintcache
          node_modules/.cache
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-build-lint-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-lint-
